services:
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin_airflow
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD : admin
    ports:
      - "5051:80"
    networks:
      - airflow

    
networks:
  airflow:
  